### ISSUE TITLE
Directory Not Found

### ISSUE THREAD

**Issue by midnite81** [pestphp/pest-plugin-type-coverage#10] opened 2023-08-15 16:08 UTC
I'm getting an error when running 

```
./vendor/bin/pest --type-coverage
```

This is the error it's outputting. DirectoryNotFoundException.
```
at vendor/symfony/finder/Finder.php:640
    636▕             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? \GLOB_BRACE : 0) | \GLOB_ONLYDIR | \GLOB_NOSORT)) {
    637▕                 sort($glob);
    638▕                 $resolvedDirs[] = array_map($this->normalizeDir(...), $glob);
    639▕             } else {
  ➜ 640▕                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    641▕             }
    642▕         }
    643▕ 
    644▕         $this->dirs = array_merge($this->dirs, ...$resolvedDirs);
```

**Comment by ashleyevans** [comment] 2023-09-19 12:30
I'm also getting this error, it's trying to load an empty directory by the looks of it

> The "" directory does not exist.

**Comment by ashleyevans** [comment] 2023-09-19 14:03
This was caused by the phpunit.xml including both the app/ and src/ directory by default when running pest --init

```
<source>
    <include>
        <directory suffix=".php">./app</directory>
        <directory suffix=".php">./src</directory>
    </include>
</source>
```

In my case I am developing a laravel package, so by removing the ./app line the issue goes away and the Type Coverage test completes successfully

**Comment by devajmeireles** [comment] 2023-10-01 22:15
Thanks for your report, @midnite81 .

As mentioned above, this is not an issue with the plugin, but yes a bad configuration related to your `phpunit.xml` file.

To preserve a better organization, I will close this issue. Feel free to open a new issue whenever necessary.

**Closed by devajmeireles** 2023-10-01 22:15 UTC
