### ISSUE TITLE
Argument #9 ($signatureMapProvider) must be of type PHPStan\Reflection\SignatureMap\SignatureMapProvider, PHPStan\PhpDoc\PhpDocInheritanceResolver given

### ISSUE THREAD

**Issue by stefro** [pestphp/pest-plugin-type-coverage#16] opened 2023-11-20 06:57 UTC
Hi,

I'm using the type coverage in my package development for https://github.com/stefro/laravel-lang-country

It has been working perfectly, but suddenly it fails in CI on these cominations:
* PHP 8.1 - Laravel 10 - prefer-stable
* PHP 8.2 - Laravel 10 - prefer-stable
![CleanShot 2023-11-20 at 07 55 07](https://github.com/pestphp/pest-plugin-type-coverage/assets/5249559/11b8a426-6482-4a1d-aaa0-ddd58af458bc)

Other combinations work well.

```
PHPStan\Analyser\NodeScopeResolver::__construct(): Argument #9 ($signatureMapProvider) must be of type PHPStan\Reflection\SignatureMap\SignatureMapProvider, PHPStan\PhpDoc\PhpDocInheritanceResolver given, called in /home/runner/work/laravel-lang-country/laravel-lang-country/vendor/pestphp/pest-plugin-type-coverage/src/PHPStanAnalyser.php on line 50

  at phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:313
    309▕     /**
    310▕      * @param string[][] $earlyTerminatingMethodCalls className(string) => methods(string[])
    311▕      * @param array<int, string> $earlyTerminatingFunctionCalls
    312▕      */
  ➜ 313▕     public function __construct(ReflectionProvider $reflectionProvider, InitializerExprTypeResolver $initializerExprTypeResolver, Reflector $reflector, ClassReflectionExtensionRegistryProvider $classReflectionExtensionRegistryProvider, Parser $parser, FileTypeMapper $fileTypeMapper, StubPhpDocProvider $stubPhpDocProvider, PhpVersion $phpVersion, SignatureMapProvider $signatureMapProvider, PhpDocInheritanceResolver $phpDocInheritanceResolver, FileHelper $fileHelper, \PHPStan\Analyser\TypeSpecifier $typeSpecifier, DynamicThrowTypeExtensionProvider $dynamicThrowTypeExtensionProvider, ReadWritePropertiesExtensionProvider $readWritePropertiesExtensionProvider, \PHPStan\Analyser\ScopeFactory $scopeFactory, bool $polluteScopeWithLoopInitialAssignments, bool $polluteScopeWithAlwaysIterableForeach, array $earlyTerminatingMethodCalls, array $earlyTerminatingFunctionCalls, bool $implicitThrows, bool $treatPhpDocTypesAsCertain, bool $detectDeadTypeInMultiCatch)
    3[14](https://github.com/stefro/laravel-lang-country/actions/runs/6914709530/job/18812838050#step:8:15)▕     {
    3[15](https://github.com/stefro/laravel-lang-country/actions/runs/6914709530/job/18812838050#step:8:16)▕         $this->reflectionProvider = $reflectionProvider;
    3[16](https://github.com/stefro/laravel-lang-country/actions/runs/6914709530/job/18812838050#step:8:17)▕         $this->initializerExprTypeResolver = $initializerExprTypeResolver;
    3[17](https://github.com/stefro/laravel-lang-country/actions/runs/6914709530/job/18812838050#step:8:18)▕         $this->reflector = $reflector;

```

Any ideas?

**Comment by sc-bruno** [comment] 2023-11-20 14:11
I had the same issue today. 
The quickest solution to get around this issue until it is resolved inside the package is to lock `phpstan` version to `1.10.41`

Add this inside `composer.json` require
`"phpstan/phpstan": "1.10.41"`

It looks like that `doctrine/dbal` internally updates `phpstan` version to `1.10.42`, creating this issue inside the package. Happened to me after the `composer update`
After the issue is resolved you can remove this line of code from your `composer.json`

**Comment by stefro** [comment] 2023-11-20 14:18
Thanks @sc-bruno for your comment. I will solve it like this until the real problem is resolved.

**Comment by gehrisandro** [comment] 2023-11-21 12:09
https://github.com/pestphp/pest-plugin-type-coverage/pull/17

**Closed** 2023-11-22 07:12 UTC
